version: '3'
services:
  php:
    build: build/php
    expose:
      - "9000"
    depends_on:
      - db
    volumes:
      - /Library/WebServer/Documents/florentsymfonychallenge:/var/www/html/symfony:cached
      - ./logs:/var/log
  web:
    build: build/nginx
    restart: always
    ports:
        - "80:80"
    depends_on:
        - php
        - db
    volumes:
        - /Library/WebServer/Documents/phpchallenge:/var/www/html/symfony:cached
        - ./logs:/var/log/nginx
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phpchallenge
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080